-- =========================================================
-- FULL SETUP: Giveaway + Voting + 1 Device = 1 Vote
-- =========================================================

-- 1) GIVEAWAY ENTRIES TABLE
create table if not exists public.giveaway_entries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  mobile_number text not null,
  age int not null,
  address text not null,
  latitude double precision,
  longitude double precision,
  purpose text not null default 'school-supply',
  vote_count int not null default 0,
  vote_points int not null default 0,
  submitted_at timestamptz not null default now()
);

-- 2) ENTRY VOTES TABLE
create table if not exists public.entry_votes (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.giveaway_entries(id) on delete cascade,
  voter_name text not null,
  voter_age int not null,
  voter_location text not null,
  device_id text not null,
  points int not null default 10,
  voted_at timestamptz not null default now()
);

-- 3) ENFORCE: ONE DEVICE = ONE VOTE
create unique index if not exists entry_votes_device_id_key
  on public.entry_votes(device_id);

-- 4) SAFE MIGRATION (kung existing na tables mo)
alter table public.giveaway_entries
  add column if not exists vote_count int not null default 0,
  add column if not exists vote_points int not null default 0;

alter table public.entry_votes
  add column if not exists device_id text;

create unique index if not exists entry_votes_device_id_key
  on public.entry_votes(device_id);

-- =========================================================
-- OPTIONAL: ENABLE RLS + BASIC POLICIES
-- =========================================================

alter table public.giveaway_entries enable row level security;
alter table public.entry_votes enable row level security;

drop policy if exists giveaway_entries_insert_policy on public.giveaway_entries;
create policy giveaway_entries_insert_policy
on public.giveaway_entries
for insert
to anon, authenticated
with check (true);

drop policy if exists giveaway_entries_select_policy on public.giveaway_entries;
create policy giveaway_entries_select_policy
on public.giveaway_entries
for select
to anon, authenticated
using (true);

drop policy if exists entry_votes_insert_policy on public.entry_votes;
create policy entry_votes_insert_policy
on public.entry_votes
for insert
to anon, authenticated
with check (true);

drop policy if exists entry_votes_select_policy on public.entry_votes;
create policy entry_votes_select_policy
on public.entry_votes
for select
to anon, authenticated
using (true);
